export const ActionTypes = {
  SET_PROD: "SET_PROD",
  SELECTED_PROD: "SELECTED_PROD",
  REMOVE_PROD: "REMOVE_PROD",
  MEN_PROD: "MEN_PROD",
  SELECTERD_MEN_PROD: "SELECTERD_MEN_PROD",
  REMOVE_MEN_PROD: "REMOVE_MEN_PROD",
  WOMEN_PROD: "WOMEN_PROD",
  SELECTERD_WOMEN_PROD: "SELECTERD_WOMEN_PROD",
  REMOVE_WOMEN_PROD: "REMOVE_WOMEN_PROD",
  ELECTRONIC_PROD: "ELECTRONIC_PROD",
  SELECTERD_ELECTRONIC_PROD: "SELECTERD_ELECTRONIC_PROD",
  REMOVE_ELECTRONIC_PROD: "REMOVE_ELECTRONIC_PROD",
  JEWELERY_PROD: "JEWELERY_PROD",
  SELECTERD_JEWELERY_PROD: "SELECTERD_JEWELERY_PROD",
  REMOVE_JEWELERY_PROD: "REMOVE_JEWELERY_PROD",
  
};
